### ISSUE TITLE
Favicons Disappearing

### ISSUE THREAD

**Issue by switzead** [bluecaret/carettab#305] opened 2022-12-02 19:08 UTC
I have selected Favicons in Quicklinks.  After visiting all the pages the icons appear as normal but when I close the browser and relaunch the browser all the icons are blank again, just the dog-eared paper image.  I am using Edge.  Latest version.  I did download the extension from the Chrome webstore but dont know if that would make a difference.  All other aspects of the extension seem to work just fine.

**Comment by switzead** [comment] 2022-12-02 19:15
Update - I removed the extension and reinstalled from the Edge Store.  Still the same issue with icons disappearing.

**Comment by bluecaret** [comment] 2022-12-03 03:11
Thank you for the bug report. I checked mine and sure enough it is happening to me as well. That is very strange. I use a basic service that has the browser supply the favicons for the extension so it should just work. I'll try to look into it soon. Wondering if it might be a bug with Edge.

**Comment by switzead** [comment] 2023-01-11 16:24
Any updates on this issue resolution?

**Comment by bluecaret** [comment] 2023-01-12 02:56
Hello, I did some initial research into this originally and it seemed to be a bug in the way that Edge provided the favicons and I wouldn't be able to do anything about it. I'm checking today though and I can't seem to duplicate the issue anymore so it's possible they have resolved the issue. Please make sure your browser is fully updated. If you are still experiencing it, I hate to say it but there isn't anything I can do about it. Thank you.

**Comment by switzead** [comment] 2023-01-12 13:38
I do have the latest version and the icons on my Favorites bar do not disappear every time I shut down Edge.  I like this app but may need to look for something different.  Thank you for looking.

**Comment by bluecaret** [comment] 2023-01-12 19:04
I'm sorry that didn't help. Unfortunately this is a result of browsers moving to a new standard called "Manifest v3" which has different requirements. One of the changes is where I pull favicons from, and the new method seems to be buggy. I'm hoping they fix it soon and that you'll return to CaretTab to try again in the future. There are probably still extensions on the old standard for now that may work better with favicons. Eventually all extensions will be required to move over though.

I'm going to look into possibly adding a way to cache the images so it doesn't try pulling it everytime or maybe even allow users to upload their own images to use for links. I can't guarantee this at the moment though.

Thank you for your support and use of CaretTab!

**Comment by switzead** [comment] 2023-01-13 13:33
I figured out why and how the icons are disappearing.  My Edge is set to delete the internet history on exit.  3 files were being deleted shown below.  When I stopped deleting the history the icons stayed.

AppData\Local\Microsoft\Edge\User Date\Profile 1\Visited Links
AppData\Local\Microsoft\Edge\User Date\Profile 1\Top Site
AppData\Local\Microsoft\Edge\User Date\Profile 1\Network Action Predictor

**Comment by bluecaret** [comment] 2023-01-13 17:53
Awesome! I should have thought of that. I do think originally it was a bug with the browser but since I wasn't able to reproduce it now they must have fixed it and then it was just a result of the clearing history. Makes sense. I'm glad you got it working and thank you for the update!

**Closed by bluecaret** 2023-01-13 17:53 UTC
Labels: bug
